In [1]:
import cv2
import numpy as np

In [15]:
image = cv2.imread('sudoku.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 150, apertureSize = 3)
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100, minLineLength=100, maxLineGap=10)

# minLineLength = min length of the line. Line segment shorter than this are rejected
# maxLineGap = Max allowed gap between line segments to treat them as single line.
print(len(lines))
print(lines)

for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
    
cv2.imshow('Edge', edges)
cv2.imshow('Image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# problem is the length of the line is infinte. To over come this problem we use HoughLinesP()

72
[[[175 412 543 412]]

 [[ 96 361 443 361]]

 [[196 459 203 244]]

 [[ 96 357 442 357]]

 [[450 250 464 521]]

 [[304 418 304  86]]

 [[252 308 254 193]]

 [[ 59 216 354 216]]

 [[351  84 354 292]]

 [[ 60 212 305 212]]

 [[199 485 207 244]]

 [[401 210 411 521]]

 [[253 396 257 144]]

 [[397 154 402 324]]

 [[ 64 169 210 169]]

 [[532 299 545 486]]

 [[ 34 516  50 335]]

 [[521 158 537 465]]

 [[450 201 466 521]]

 [[302 320 302  86]]

 [[350 271 353 499]]

 [[ 39 502  61 259]]

 [[159 221 165 115]]

 [[515  64 541 433]]

 [[289 410 476 410]]

 [[515 242 529 446]]

 [[498  70 524 448]]

 [[374 464 517 464]]

 [[499 188 519 487]]

 [[301 519 301 297]]

 [[185 171 328 171]]

 [[222 309 392 309]]

 [[138 409 305 409]]

 [[497 222 513 463]]

 [[160 260 308 260]]

 [[402 325 408 501]]

 [[255 311 407 311]]

 [[190 462 303 463]]

 [[ 22 538 127 539]]

 [[ 64 172 193 172]]

 [[509  65 532 396]]

 [[542  67 557 243]]

 [[252 465 352 466]]

 [[540  64 557 265]]

 [[443  95 450 247]]

 [[176 